# For clients based off of Bitcoin 0.9.0
---
- hosts: all
  user: root

  vars:
    main_user: multi
    coinname: bluecoin
    executable_name: {{coinname}}d
    gitrepo: https://github.com/bluecoiner/bluecoin.git
    version: master
    key: BLU
    notifier: /home/multi/powerpool_multi/notifier.py
    rpcport: 27105
    #port: 
    # disable wallet is broken for fractalcoin
    compile_flags: USE_UPNP=0 USE_IPV6=0 USE_QRCODE=0 
    payout: false
  tasks:
    - include: litecoin.yml
